### PR TITLE
don't reference deprecated functions

### PR DESCRIPTION
**Pull request by ggreif**
Removes a bunch of GHC warnings related to `NS.bindSocket` and `NS.sClose`

### CODE REVIEW

**Comment by ggreif** [comment]
The build failures on older GHCs seem to come from a broken `binary` package on those. Not my fault.

**Comment by snoyberg** [comment]
Looks like the issue with binary is being tracked upstream at https://github.com/kolmodin/binary/issues/123.

**Comment by ggreif** [comment]
@snoyberg when restarting a recent green check on travis, will it fail the same way with `binary`?

**Comment by snoyberg** [comment]
Most likely, yes. I'm just hoping that binary will end up having a quick Hackage revision to fix the problem.

**Comment by snoyberg** [comment]
I've pushed commit 93fea18 to try and fix this, let's see what happens.

**Comment by snoyberg** [comment]
Can you try rebasing on master?

**Comment by ggreif** [comment]
@snoyberg stuff looks prettier now!

**Comment by snoyberg** [comment]
Do we need any kind of lower bound on network for when the new names were introduced? I'm not sure how old the identifiers are.

**Comment by ggreif** [comment]
v2.4.0.0 should be fine: https://github.com/haskell/network/commit/4db251a7d579b3efa606f69739e18cc6f9b64d02

**Comment by snoyberg** [comment]
Cool, can you add that to this PR?

**Comment by ggreif** [comment]
@snoyberg done :-)

**Comment by snoyberg** [comment]
Cool, thanks! I'll merge once Travis goes green.

**Pull request merged**
