### PR TITLE
Add Data.Streaming.Filesystem version that works with OsPath

### PR DESCRIPTION
**Pull request by sergv**
The implementation was copied from `Data.Streaming.Filesystem` with slight modifications.

### CODE REVIEW

**Comment by snoyberg** [comment]
Builds are failing.

**Comment by sergv** [comment]
So the reason builds are  failing is because I added bound `filepath >= 1.4.100`, which claims to be compatible with `base >= 4.9`, wheras this package needs `base >= 4.12` so the bound shouldn't prevent this package from working with earlier GHCs. In `filepath >= 1.4.100` new set of modules was added which shouldn't break anyone.

However the CI runs tests with older lts releases that don't satisfy `filepath >= 1.4.100`, so they fail at dependency resolution stage. Somewhat surprisigly the nightly LTS also didn't pick up `filepath >= 1.4.100`, but it would do so at some point after which it would work. The bigger question is what to do with older LTSes which will never attain `filepath >= 1.4.100`.

**Comment by snoyberg** [comment]
This would require some conditional compilation. The simplest thing may be to put this new module in a separate package.

**Comment by sergv** [comment]
I agree that turning this into a separate package is the simplest way forward. I though there may be interest in keeping it part of `streaming-commons` since it already contains functions on `FilePath` so the package seemed to be reasonable place where one would expect to find same API but for `OsPath`.

**Pull request closed without merging**
